### ISSUE TITLE
Feature enhancement: Make channel topic field a text area, instead of a single line field.

### ISSUE THREAD

**Issue by kattekrab** [RocketChat/Rocket.Chat.Ops#46]
HI there!

I love rocketchat - thanks so much for creating this awesome open source chat tool.

I'd love to see a tweak to the Topic field entry, to make it a bit easier to edit long strings.

We put a bunch of project shortcuts at the top of the channel - and this can get unwieldy to edit with a series of long URLS....  

![rocketchat-roominfo](https://user-images.githubusercontent.com/172755/42362517-02cedd90-8137-11e8-84bd-dcf00fff4133.png)

**Comment by geekgonecrazy** [comment]
Luckily I saw this.  This repo is not our main one, so issues here are rarely seen.  Best place for visibility on feature requests is feature request category on our forum.  https://forums.rocket.chat

Going to go ahead and close so it doesn't sit here open for all of eternity :)
